## **RED ANT MEDIA - CODING CHALLENGE**

---

1.   NAME     : BAALA VIDHYA SREE K C
2.   ROLL NUM : 1832011
3.   DEPT     : DATA SCIENCE

---

ATTENDED QUESTION NUMBER : **3**

---

###### **IMPORTING REQUIRED LIBRARIES**

In [1]:
import numpy as np

###### **GRID PATTERN**

Here, we consider a ***9 X 9 SUDOKU PUZZLE***  

In [2]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

##### **TO CHECK IF THE CELL IS OCCUPIED**

To check the cell in terms of row wise, column wise and subgrid wise (3 X 3 matrices)

In [3]:
def possible(row, column, number):
    global grid
    for i in range(0,9):
        if grid[row][i] == number:
            return False

    for i in range(0,9):
        if grid[i][column] == number:
            return False
    
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

##### **SUDOKU VALIDATION**

To check if the grid pattern is valid or not.

In [4]:
def isValidSudoku(grid):
  for i in range(9):
      row = {}
      column = {}
      block = {}
      row_cube = 3 * (i//3)
      column_cube = 3 * (i%3)
      for j in range(9):
        if grid[i][j]!=0 and grid[i][j] in row:
          return False
        row[grid[i][j]] = 1
        if grid[j][i]!=0 and grid[j][i] in column:
          return False
        column[grid[j][i]] = 1
        rc= row_cube+j//3
        cc = column_cube + j%3
        if grid[rc][cc] in block and grid[rc][cc]!=0:
          return False
        block[grid[rc][cc]]=1
  return True

isValidSudoku(grid)

True

##### **SOLVING THE GRID**

Based on validity, this definition will solve the grid and return ALL POSSIBLE SOLUTIONS for the Sudoku puzzle (only when VALID).

If the Sudoku Pattern is INVALID, then it return NO SOLUTION

In [5]:
def solve():
  global grid
  if isValidSudoku(grid) == False:
    print('NO SOLUTION since Grid is INVALID!')
  else:
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0
                return
    print('Solution \n', np.matrix(grid))
    input('More possible solutions')

solve()

Solution 
 [[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions
Solution 
 [[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More possible solutions
